import { chromium } from '@playwright/test';
import { mkdir, rename } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { homedir } from 'node:os';
import path from 'node:path';

await mkdir('artifacts/raw-video', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', args: ['--use-angle=swiftshader', '--enable-webgl'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1160 }, recordVideo: { dir: 'artifacts/raw-video', size: { width: 1440, height: 1160 } } });
const page = await context.newPage();
await page.goto('http://127.0.0.1:5173');
await page.getByLabel('Your name', { exact: true }).fill('Maya');
await page.getByRole('radio', { name: 'Generic Female', exact: true }).click();
await page.getByRole('radio', { name: /Level 1/ }).click();
await page.getByRole('button', { name: 'Start', exact: true }).click();
await page.locator('[data-city-ready="true"]').waitFor();
await page.evaluate(() => {
  const caption = document.createElement('div'); caption.id = 'demo-caption';
  caption.style.cssText = 'position:fixed;bottom:12px;left:50%;transform:translateX(-50%);z-index:1000;background:#294b39f5;color:#fffef5;padding:14px 26px;border-radius:10px;box-shadow:0 4px 24px #23382722;font:500 16px Manrope,sans-serif;text-align:center;width:max-content;max-width:90%;pointer-events:none';
  document.body.appendChild(caption);
});
const started = Date.now();
const caption = text => page.evaluate(text => { document.getElementById('demo-caption').textContent = text; }, text);
const at = async seconds => { const remaining = started + seconds * 1000 - Date.now(); if (remaining > 0) await page.waitForTimeout(remaining); };
const pick = name => page.getByRole('button', { name, exact: true }).click();
const decision = pick;
await caption('Age 18. A first job. Your money story starts here.');
await at(4); await decision('Start working'); await decision('No — keep it in cash');
await caption('A $200 medical bill. An empty emergency fund. Time to call Mom.');
await pick('Take money from my emergency fund'); await decision('Call Mom to ask for money :(');
await at(15); await pick('Open an account'); await pick('TFSA');
await caption('A birthday gift opens an account. A raise can build an investing habit.');
await pick('Buy one ETF'); await pick('QQQ');
await at(29);
await caption('Watch the monthly market change. More risk does not always pay off.');
await at(35); await pick('Buy a penthouse in Miami');
await caption('Penthouse dreams meet the actual balance. Rent for a day, or keep grinding.');
await at(43); await pick('See my options'); await pick('Rent a penthouse to larp and sell a course');
await page.getByRole('heading', { name: 'Your choices added up.' }).waitFor();
await caption('Six months of choices. One clear picture of your finances.');
await at(50); await page.getByRole('button', { name: 'Compare your paths' }).click();
await at(57); await caption('Investly makes your money choices visible.');
await at(61); await page.waitForTimeout(5000);
const video = page.video(); await context.close(); await browser.close();
const source = await video.path();
const encoder = path.join(homedir(), 'Library/Caches/ms-playwright/ffmpeg-1011/ffmpeg-mac');
const output = 'artifacts/pitch-demo.webm';
// Preserve the entire journey, including the final goal, within one minute.
const probe = spawnSync(encoder, ['-i', source], { encoding: 'utf8' });
const duration = probe.stderr?.match(/Duration: (\d+):(\d+):(\d+(?:\.\d+)?)/);
const seconds = duration ? Number(duration[1]) * 3600 + Number(duration[2]) * 60 + Number(duration[3]) : 0;
const result = seconds > 0 ? spawnSync(encoder, ['-y', '-itsscale', String(60 / seconds), '-i', source, '-t', '60', '-c:v', 'libvpx', '-deadline', 'realtime', '-cpu-used', '8', '-threads', '4', '-b:v', '2200k', output], { encoding: 'utf8' }) : { status: 1, stderr: 'Could not read capture duration.' };
if (result.status !== 0) { await rename(source, output); console.warn('Saved untrimmed capture; encoder output:', result.stderr); }
console.log(`Recorded ${output}`);
